require "json"
require "yaml"
require "fileutils"
require_relative "shell"

module Media
  # The spoken master track of an explainer (no song): prompts/narration/narration.yml orders the TTS lines generated by
  # `SFX=<sfx> sfx:gen` (sounds with tts:/voice:, see Media::Sfx) and places them on one timeline:
  #   sfx: narration            the sfx config whose output/<sfx>/sounds/<sound>.wav + .json (timestamps) are used
  #   lead_in / tail / gap      seconds before the first line, after the last, default pause between lines
  #   trim_db / target_db       silence trim threshold and per-line RMS level
  #   out / words / stems / lines_out   master wav (the project's audio/source.wav), global word timings, per-speaker stems dir
  #   lines: [{ sound:, speaker:, gap: | at: | overlap:, gain_db: }]
  # build writes the master, a full-length stem per speaker (H3 lip-sync input, same grid as the master), words.json
  # ([{w, s, e, speaker, line}] in master seconds, from the ElevenLabs timestamps) and a lines report, then prints a timing table.
  class Narration < Shell
    ROOT = File.expand_path("../..", __dir__)

    def initialize(config = File.join(ROOT, "prompts", "narration", "narration.yml"))
      @config = YAML.safe_load_file(config)
    end

    def sounds_dir = File.join(ROOT, "output", @config.fetch("sfx", "narration"), "sounds")
    def abs(path) = File.expand_path(path, ROOT)

    def build
      raise "Write narration lines before narration:build" if @config.fetch("lines").empty?
      lines = @config.fetch("lines").map do |line|
        wav = File.join(sounds_dir, "#{line.fetch("sound")}.wav")
        raise "narration line #{line["sound"]} not generated yet (SFX=#{@config.fetch("sfx", "narration")} sfx:gen)" unless File.exist?(wav)
        line.merge("wav" => wav)
      end
      plan = @config.slice("lead_in", "tail", "gap", "trim_db", "target_db").merge(
        "rate" => 48_000, "out" => abs(@config.fetch("out", "audio/source.wav")), "stems" => abs(@config.fetch("stems", "audio/stems")),
        "lines" => lines
      )
      plan_path = File.join(ROOT, "output", @config.fetch("sfx", "narration"), "narration_plan.json")
      FileUtils.mkdir_p(File.dirname(plan_path))
      File.write(plan_path, JSON.pretty_generate(plan))
      python = Media::Python.new
      report = JSON.parse(run(python.executable, File.join(Media::Python::SCRIPTS, "narration_mix.py"), plan_path, quiet: true))
      words = report["lines"].flat_map { |placed| line_words(placed) }
      words_path = abs(@config.fetch("words", "audio/words.json"))
      File.write(words_path, JSON.pretty_generate(words))
      File.write(abs(@config.fetch("lines_out", "audio/lines.json")), JSON.pretty_generate(report))
      { out: plan["out"], duration: report["duration"], frames: (report["duration"] * 24).ceil, words: words_path, count: words.size,
        timing: report["lines"].map { |l| format("%-6s %-8s %7.3fs f%-5d +%.2fs", l["sound"], l["speaker"], l["at"], (l["at"] * 24).floor, l["dur"]) } }
    end

    private

    # ElevenLabs word timestamps (line-local, before trimming) shifted onto the master timeline.
    def line_words(placed)
      meta = JSON.parse(File.read(File.join(sounds_dir, "#{placed["sound"]}.json")))
      shift = placed["at"] - placed["trim"]
      stamps = Array(meta["timestamps"])
      return char_words(stamps, shift, placed) if stamps.first.is_a?(Hash) && stamps.first.key?("characters")
      stamps.filter_map do |ts|
        text = ts["text"] || ts["word"] || ts["w"]
        start = ts["start"] || ts["start_time"] || ts["s"]
        stop = ts["end"] || ts["end_time"] || ts["e"]
        next if text.nil? || start.nil? || text.to_s.strip.empty?
        { w: text.to_s.strip, s: (start + shift).round(3), e: ((stop || start) + shift).round(3), speaker: placed["speaker"], line: placed["sound"] }
      end
    end

    # ElevenLabs alignment chunks: { characters: [...], character_start_times_seconds: [...], character_end_times_seconds: [...] }.
    # Characters are joined across chunks and split into words at whitespace.
    def char_words(chunks, shift, placed)
      chars = chunks.flat_map do |c|
        c["characters"].zip(c["character_start_times_seconds"], c["character_end_times_seconds"])
      end
      words, cur = [], []
      flush = lambda do
        text = cur.map(&:first).join.strip
        words << { w: text, s: (cur.first[1] + shift).round(3), e: (cur.last[2] + shift).round(3), speaker: placed["speaker"], line: placed["sound"] } unless text.empty?
        cur = []
      end
      chars.each { |ch| ch[0].match?(/\s/) ? (flush.call unless cur.empty?) : cur << ch }
      flush.call unless cur.empty?
      words
    end
  end
end
